Wacom Support, absolute x,y pressure; relative scroll; forward/back buttons; platform address width case for event timestamp
jtgans/cl-evdev pull request #3
Opened 2017-04-06 01:57 UTC by olewhalehunter

Wacom Support, absolute x,y pressure; relative scroll; forward/back buttons; platform address width case for event timestamp

library will not work on 32 bit systems without unsigned-long-integer case fix included in this commit

tested on Wacom CTE-440 and Lenovo Black Silk keyboard

2017-04-10 19:46 UTC, jtgans commented on evdev.lisp
> +(cond ((equal (machine-type) "X86")
This concerns me a bit -- with this change, it'll only work on x86-based machines. ARM boxen are effectively out.

2017-04-10 19:47 UTC, jtgans commented on evdev.lisp
> +from raw evdev data. Unix time values bit widths differ on 32/64bit systems."))
We'll want to note here that the difference is based upon the return value of machine-type.

2017-04-10 19:49 UTC, jtgans requested changes
Adjust the comment and I'll happily take this change. =o)

2017-04-10 20:23 UTC, olewhalehunter commented
Documentation adjusted in input-event-struct per requested changes.

2017-04-19 20:27 UTC, jtgans approved these changes

2017-04-19 20:27 UTC, merged